name: Count courses

on:
  push:
  pull_request:

jobs:
  courseCounter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the number of courses
        run: |
          echo "NCOURSES=`grep -c "\[website\]"`" >> $GITHUB_ENV
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5dd50ff10dbb3fe3222aa8ac658878bf
          filename: ncourses.json
          label: Number of courses
          message: is ${{ env.NCOURSES }}
          valColorRange: ${{ env.NCOURSES }}
          maxColorRange: 100
          minColorRange: 0
